### ISSUE TITLE
Can't override array values

### ISSUE THREAD

**Issue by devDomM** [bahmutov/cypress-extends#51]
Setup is really simple. The cypress.json contains the following config value:
`{
   "langArray": ["en", "de"]
}`
and another json file, e.g. custom.json, which extends the cypress.json looks like this:
`{
   "extends": "./cypress.json",
   "langArray": ["es", "fr"]
}`

When calling cypress.io with the custom.json config, we would expect "langArray" only contains the values "**es**" and "**fr**". However, the arrays were merged and the result contains **all four** values.
`"langArray": ["en", "de", "es", "fr"]`

Is this behaviour intended? If not, it would be great to have this changed.

**Comment by bahmutov** [comment]
I think at this point it becomes hard to say - some people would love them merged, others would say replace. That's why it would be better to write the extends logic in the plugin file. Then you have the full control over merging. I think a nice feature addition to this plugin would be a function to do the merge.

**Comment by devDomM** [comment]
Thanks for your feedback, I think we can close this issue then.
